"""Added unit measurements table

Revision ID: 010556c049e4
Revises: 181026def40c
Create Date: 2026-01-15 13:51:28.968406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "010556c049e4"
down_revision: Union[str, Sequence[str], None] = "181026def40c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unit_measurement",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("short_name", sa.String(), nullable=False),
        sa.Column("min_unit_measurement_id", sa.UUID(), nullable=True),
        sa.Column("quantity_in_min_unit", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["min_unit_measurement_id"],
            ["unit_measurement.id"],
            name="unit_measurement_min_unit_measurement_id_fk",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unit_measurement")
    # ### end Alembic commands ###
