"""Added user_promocode_assignment

Revision ID: 026b3433f7eb
Revises: 4a1949321cce
Create Date: 2026-01-15 14:45:12.787871

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "026b3433f7eb"
down_revision: Union[str, Sequence[str], None] = "4a1949321cce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_promocode_assignment",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("promocode_id", sa.UUID(), nullable=False),
        sa.Column("is_refunded", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["promocode_id"],
            ["promocode.id"],
            name="user_promocode_assignment_promocode_id_foreign_key",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_promocode_assignment_user_id_foreign_key", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_promocode_assignment")
    # ### end Alembic commands ###
