"""Added payment table

Revision ID: 086dd28ba621
Revises: 026b3433f7eb
Create Date: 2026-01-15 14:47:01.198080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "086dd28ba621"
down_revision: Union[str, Sequence[str], None] = "026b3433f7eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("foreign_id", sa.String(), nullable=True),
        sa.Column("payment_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("system", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment")
    # ### end Alembic commands ###
