"""Added group_product_assignment table

Revision ID: 1f6b5473b77b
Revises: 9f461245299b
Create Date: 2026-01-15 13:53:38.673633

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f6b5473b77b"
down_revision: Union[str, Sequence[str], None] = "9f461245299b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_product_assignment",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("product_value", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["group.id"], name="group_product_assignment_group_id_fk", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name="group_product_assignment_product_id_fk", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_product_assignment")
    # ### end Alembic commands ###
