"""Added promocodes

Revision ID: 4a1949321cce
Revises: 508c5e1c2ed0
Create Date: 2026-01-15 14:13:07.959123

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4a1949321cce"
down_revision: Union[str, Sequence[str], None] = "508c5e1c2ed0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promocode",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("active_until_date", sa.DateTime(), nullable=True),
        sa.Column("is_combined_w_other_promotions", sa.Boolean(), nullable=False),
        sa.Column("how_many_times_per_user", sa.SmallInteger(), nullable=False),
        sa.Column(
            "discount_type", postgresql.ENUM("per_basket", "per_items", name="discount_type_enum"), nullable=False
        ),
        sa.Column("included_products_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("excluded_products_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "NOT (included_products_ids IS NOT NULL AND excluded_products_ids IS NOT NULL)", name="check_promocode"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("promocode")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS discount_type_enum")
