"""Added deliveries table

Revision ID: 4fb5de3b0316
Revises: 086dd28ba621
Create Date: 2026-01-15 14:49:01.109870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4fb5de3b0316"
down_revision: Union[str, Sequence[str], None] = "086dd28ba621"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("delivery_system", sa.String(), nullable=False),
        sa.Column("delivery_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("foreign_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("delivery")
    # ### end Alembic commands ###
