"""Added reviews

Revision ID: 508c5e1c2ed0
Revises: c4c7aa575727
Create Date: 2026-01-15 14:11:07.676336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "508c5e1c2ed0"
down_revision: Union[str, Sequence[str], None] = "c4c7aa575727"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("parameter_id", sa.UUID(), nullable=False),
        sa.Column("stars", sa.SmallInteger(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.CheckConstraint("stars >= 1 and stars <= 5", name="check_review_stars"),
        sa.ForeignKeyConstraint(
            ["parameter_id"], ["product_parameter.id"], name="review_parameter_id_fk", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="review_user_id_fk", ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review")
    # ### end Alembic commands ###
