"""added text_color_code and renamed banner_color_code

Revision ID: 5bbf27db8016
Revises: dee68d104774
Create Date: 2026-01-19 11:03:20.654672

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5bbf27db8016"
down_revision: Union[str, Sequence[str], None] = "dee68d104774"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mark", sa.Column("banner_color_code", sa.String(length=8), nullable=False))
    op.add_column("mark", sa.Column("text_color_code", sa.String(length=8), nullable=False))
    op.drop_column("mark", "color_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mark", sa.Column("color_code", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("mark", "text_color_code")
    op.drop_column("mark", "banner_color_code")
    # ### end Alembic commands ###
