"""Added media_link

Revision ID: 78ee845b9a8c
Revises: afa8bd55370a
Create Date: 2026-01-15 14:53:59.988976

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "78ee845b9a8c"
down_revision: Union[str, Sequence[str], None] = "afa8bd55370a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_link",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("media_id", sa.UUID(), nullable=False),
        sa.Column(
            "entity_type", postgresql.ENUM("product", "category", "review", name="entity_type_enum"), nullable=False
        ),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("alt_text", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"], name="media_link_media_id_fk", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("media_link")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS entity_type_enum")
