"""Added media

Revision ID: afa8bd55370a
Revises: d4e8b0b49dfb
Create Date: 2026-01-15 14:52:15.957173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "afa8bd55370a"
down_revision: Union[str, Sequence[str], None] = "d4e8b0b49dfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("image", "video", "text", "audio", "document", name="media_type_enum"),
            nullable=False,
        ),
        sa.Column("original_url", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("additional_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("media")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS media_type_enum")
