"""old_price in ProductParameter can be Null

Revision ID: b29f13dc838d
Revises: 5bbf27db8016
Create Date: 2026-01-28 02:02:47.643932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b29f13dc838d"
down_revision: Union[str, Sequence[str], None] = "5bbf27db8016"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product_parameter", "old_price", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product_parameter", "old_price", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
