"""Added orders table

Revision ID: d4e8b0b49dfb
Revises: 4fb5de3b0316
Create Date: 2026-01-15 14:50:09.173947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4e8b0b49dfb"
down_revision: Union[str, Sequence[str], None] = "4fb5de3b0316"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("goods_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["delivery_id"], ["delivery.id"], name="order_delivery_id_fk", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["payment_id"], ["payment.id"], name="order_payment_id_fk", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="order_user_id_fk", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order")
    # ### end Alembic commands ###
