"""Added product's characteristics table

Revision ID: da810b1119c2
Revises: 010556c049e4
Create Date: 2026-01-15 13:52:24.663302

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da810b1119c2"
down_revision: Union[str, Sequence[str], None] = "010556c049e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_characteristic",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("text_value", sa.String(), nullable=True),
        sa.Column("num_value", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_text_value", sa.Boolean(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("is_for_filter", sa.Boolean(), nullable=False),
        sa.Column("unit_measurement_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "NOT (is_visible = false AND is_for_filter = false)", name="check_visible_filter_characteristic"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name="product_characteristic_product_id_fk", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["unit_measurement_id"],
            ["unit_measurement.id"],
            name="product_characteristic_unit_measurement_id_fk",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_characteristic")
    # ### end Alembic commands ###
