"""Added media_variant

Revision ID: dee68d104774
Revises: 78ee845b9a8c
Create Date: 2026-01-15 14:55:00.617223

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dee68d104774"
down_revision: Union[str, Sequence[str], None] = "78ee845b9a8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_variant",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("media_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("quality", sa.SmallInteger(), nullable=True),
        sa.Column("format", postgresql.ENUM("webp", "jpg", "png", name="media_variant_enum"), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("additional_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"], name="media_variant_media_id_fk", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("media_variant")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS media_variant_enum")
