"""Added product_mark_assignment

Revision ID: ffda5de655cb
Revises: b4a8442eacf7
Create Date: 2026-01-15 14:08:48.229439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffda5de655cb"
down_revision: Union[str, Sequence[str], None] = "b4a8442eacf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_mark_assignment",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("mark_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mark_id"], ["mark.id"], name="product_mark_assignment_mark_id_fk", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name="product_mark_assignment_product_id_fk", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_mark_assignment")
    # ### end Alembic commands ###
